### PR TITLE
MSSQL - Allow Insert of Primary Keys When Identity is Not Defined for the Table.

### PR DESCRIPTION
**Pull request by turnkey-commerce**
This PR resolves Issue #28 for MSSQL for the case when an Identity is not defined for the PK in a table.  It is implemented the same methodology as the previous pull request for Postgres/MySQL/SQLite.

There is no similar automatic way to do this for the Oracle database so this should finalize Issue #28 to the extent possible.

### CODE REVIEW

**Comment by kenshaw** [comment]
Thanks for the submission! Bit busy now, but will review in the next couple days and merge. Again, thanks!

**Comment by turnkey-commerce** [comment]
Thanks for the update and you're welcome!

**Comment by kenshaw** [comment]
Added to master; again thank you for your high quality work!

**Comment by turnkey-commerce** [comment]
You're welcome!

**Pull request merged**
