### PR TITLE
sqlite3 - Detect INTEGER PRIMARY KEY as not manualpk

### LINKED ISSUE #85: SQLite3 primary key for INTEGER PRIMARY KEY column requires manual primary key
As mentioned in a previous issue:

> Based on the SQLite documentation: [SQlite docs reference](http://sqlite.org/autoinc.html)
> 
> > On an INSERT, if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use. This is true regardless of whether or not the AUTOINCREMENT keyword is used.
> For SQLite3 if a row is defined with INTEGER PRIMARY KEY then I think it would be reasonable to not add those fields in insert/save methods.

This issue is separate and is specifically related to detecting when Primary Key does not need to be manually set (when using Sqlite3).

### PR DESCRIPTION
**Pull request by Goblinlordx**
close #85
I can't say I am exactly fond of this method (table info will be queried up to 2x per table) but it should suffice.  Considering I don't feel performance (during generation) that significant for this case.  I wanted to accomplish this with as little change as possible.

**note:** this change will cause previously generated code (for sqlite3) to be different.

### CODE REVIEW

**Comment by kenshaw** [comment]
No -- you shouldn't worry about performance during this generation step. That's kind of why xo is messy to begin with -- it's meant to as a developer tool that is run "occasionally" when a schema changes or some such.

Really appreciate the fixes you sent over today!

**Comment by Goblinlordx** [comment]
:+1:
Was this meant to be merged and closed (as opposed to be just closed)?

**Comment by kenshaw** [comment]
I prefer not to use merge, and instead rebase commits (makes for much cleaner commit history). This meant that your commit has a different hash in master:

https://github.com/knq/xo/commit/f2a9ad3269d985ee098d10e1ec65ca5c0a33ab22

The version you had branched off of had diverged from master as I had this morning pushed a couple of different commits to master.

**Comment by Goblinlordx** [comment]
Ah ok

**Pull request closed without merging**
