### PR TITLE
Expect integer, not boolean, from pragma pk column in sqlite

### PR DESCRIPTION
**Pull request by jchamberlain**
Addresses #42. I'm a first-time user of xo and ran into this bug right away. I know in the issue you mention this requiring some rewrites and time investment, so I'm probably missing something, but for my own purposes this quick fix was all I needed to get off the ground.

### CODE REVIEW

**Comment by jchamberlain** [comment]
Oh, and now I see the problem haha. Let me play with this some more and I'll update the PR.

**Comment by kenshaw** [comment]
I believe this change would introduce problems for the other database types. Unfortunately, `xo` can't handle every schema type for every database. If you're able to get this to work with the other databases, please create a new PR and I'll look at it.

**Comment by jchamberlain** [comment]
To be clear, the actual problem I'm seeing is that xo doesn't support compound primary keys, regardless of database type. The error I encountered and found described in #42 is just the Sqlite-specific manifestation of this missing feature. Is that correct?

So if I'm to open a new PR, it really needs to be one adding support for compound primary keys for all database types. Is that something you would to open to?

(I just tried it, and xo "successfully" generates *invalid* code for compound primary keys in Postgres, but dies trying in Sqlite. My PR "fixes" the Sqlite loader so that it too can successfully generate *invalid* code, which of course is worthless. My bad. Also, I'd say #28 and #42 are just different versions of the same underlying issue.)

**Comment by kenshaw** [comment]
Yes, the issue in general is compound primary keys. The problem with supporting that in Postgres, at least, is I don't have the time to do the research needed on the postgres docs to determine the right way to detect that case. I haven't even looked at doing it it SQLite. I agree this would be helpful for xo to detect (and generate code for), and so I'm willing to consider a pull request that can enable that functionality for PG/SQLite/etc.

**Comment by jchamberlain** [comment]
Cool. MySQL/Postgres/Sqlite won't be a problem for me, so I'll have to look at the others to see how it should be done. No promises, but I'd love to contribute this if I can set aside some time in the next couple weeks. It's a great project you've got here and I appreciate all the work you've already put into it!

**Pull request closed without merging**
