### PR TITLE
Remove unused flags

### PR DESCRIPTION
**Pull request by nathanleclaire**
@kenshaw 

While poking around I noticed that these don't seem to be referenced anywhere?

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by kenshaw** [comment]
Yes -- I have a local branch that I've never pushed that has support for excluding / including types.

**Comment by kenshaw** [comment]
I get a conflict with your last PR. If you redo against the new master, I will merge this.

**Comment by nathanleclaire** [comment]
Realized a bit late that this doesn't really help on `SELECT` either -- will chew on it a bit and get back to you.

**Comment by nathanleclaire** [comment]
@kenshaw Rebased and ready to go!

**Comment by nathanleclaire** [comment]
BTW, thanks for working on and open sourcing this program!

**Pull request merged**
