### PR TITLE
Add MySQL types and generate JSON tags

### PR DESCRIPTION
**Pull request by dgnorton**
- Map MySQL types to Go types
  - `bit` -> `bool`
  - `date` -> `*time.Time`
- Add JSON tags to structs generated for MySQL

### CODE REVIEW

**Comment by kenshaw** [comment]
I have no problem merging this -- but can you do a couple things:

1) Add the json tags to the other *.type.go.tpl files as well. After I merge this commit, I will also add an option to disable the json tag generation (or something else), but I'd like the types to be consistent

2) Please collapse the commit history to a single commit (`git rebase -i`)

Thanks!

**Comment by dgnorton** [comment]
@kenshaw added json tags to the other tpl files but I'm not set up to test those DBs.

**Comment by kenshaw** [comment]
I've merged this, however I do believe the `bit` addition for MySQL is incorrect. I believe it should be a `[]uint8`, with a special case when the column precision is 1. This also needs to be fixed in the other databases. I didn't catch this originally, as I don't personally use bit column types.

I'm in the middle of 2 fairly large rewrites, one not related to this, and another that is related to better standardizing the type parsing. I should have those changes done relatively soon, and will push them out when available.

**Comment by kenshaw** [comment]
BTW, thanks for the submission!

**Comment by dgnorton** [comment]
I agree about the `bit` type. It didn't look like the precision making it down to the type conversion function though. Should I wait for the rewrite or is it worth looking into fixing it in the interim?

You're welcome and thank you for making this tool available.

**Comment by kenshaw** [comment]
I believe all of the various database `Loader`s produce the database datatype (`dt`) in the format of `type(precision)` but I could be wrong (or the MySQL schema query isn't returning that).

You're more than welcome to work on it more and submit other pull requests, as I haven't started the rewriting of the type parsing.

**Comment by dgnorton** [comment]
You're right. I didn't see the `ParsePrecision` call.

**Pull request merged**
