### PR TITLE
Added ability to specify automatically set fields on Update and Insert operations

### PR DESCRIPTION
**Pull request by mccolljr**
I added a section to the README.md which explains what I've done,
but the short version is that I enabled some command-line options which allow the user to specify columns to be set on INSERT and UPDATE operations, along with the values those columns should be set to (in the form of an expression, which is trusted to be valid Go in the context of the generated file)

Example use would be
```sh
xo mysql://user:pass@localhost/db --include [type] --autofields \
--oninsert [columnC]=[expressionC] \
--onupdate [columnA]=[expressionA] [columnB]=[expressionB]
```

I've found this quite useful myself, so if things appear up to par I thought it would be nice to include this in the core library.

### CODE REVIEW

**Comment by mccolljr** [comment]
I realized after originally submitting this pull request that support for inclusion/exclusion wasn't yet included, so I added some lines to internal/loader.go to handle that. This should be the final version of this pull request.

**Comment by kenshaw** [comment]
Thanks for this. I'm looking at it, but may not have enough time to get through it all today.

**Comment by mccolljr** [comment]
Thanks for reviewing, looking forward to your comments.

**Comment by kenshaw** [comment]
Sorry for taking so long on this -- I've been slammed this week. I promise I will review this this weekend and make a decision.

**Comment by mccolljr** [comment]
Hey, I just wanted to touch base and see if this would make the cut or if you'd like me to make some changes, etc.

**Comment by kenshaw** [comment]
Sorry about not getting back to you sooner. The primary issue is that I don't believe this is the right approach for xo -- instead I think it should be some kind of combination of CLI parameters and custom templates. The problem is that it is almost impossible to create something that works for all database types consistently. I have been working on some other SQL CLI utilities, and I think I have an idea of what would work for this scenario.

Part of the issue is that the database should be the "only source of truth" and when you start putting things like "ignore this field on update" into your generation scripts, then part of the database logic ("truth") gets shuffled into the shell script or batch file or whatever you're using to generate the code. Since triggers aren't universal across databases, I don't know how this would be able to be fit in. I've been thinking about the issue, and I think I have a more generic way to do this, but have not yet had time to implement it.

**Pull request closed without merging**
