### PR TITLE
Add custom template example

### PR DESCRIPTION
**Pull request by nathanleclaire**
Came up with this solution and thought others might find it interesting, for this reason as well as for others.  I was a bit stuck on the lack of "aggregate" / group methods available out of the box, but writing custom templates is v. powerful ! (albeit a bit intimidating :) so I hope this helps others)

cc @kenshaw @dgnorton what do you think?

thanks !  

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by kenshaw** [comment]
I am genuinely surprised that anyone has gone to such extents to understand the code, as clearly you have. Thanks! I will review this and will likely merge unless there are any glaring oversights.

**Comment by nathanleclaire** [comment]
> I am genuinely surprised that anyone has gone to such extents to understand the code, as clearly you have.

Ha ha!  I know the feeling.  That's a great one!

> Thanks! I will review this and will likely merge unless there are any glaring oversights.

:+1:

**Comment by kenshaw** [comment]
I appreciate the example in the README. Unfortunately, xo is not really a polished tool in terms of documentation, and one of the greatest issues/confusions is over writing custom templates (based on the repeated issues opened here). Anyways, you might want to take a look at one of the `gen.sh` files in the project. Typically, in the custom templates I've developed (that aren't public), we keep the queries as raw SQL and use xo to generate it from the SQL. It's the same way that xo generates its own models for working against the database:

```sh
$ xo $PGDB -N -M -B -T Enum -F PgEnums --query-type-comment "$COMMENT" -o $DEST $EXTRA << ENDSQL
SELECT
  t.typname::varchar AS enum_name
FROM pg_type t
  JOIN ONLY pg_namespace n ON n.oid = t.typnamespace
  JOIN ONLY pg_enum e ON t.oid = e.enumtypid
WHERE n.nspname = %%schema string%%
ENDSQL
```

For instance, we would do it this way for things like your `MostRecent` example, since not every table may have a `created` or `modified` field as the case may be. I hope people can understand that the reason I chose to keep this kind of stuff out of xo's basic templates is that it would be unwieldy to support every single use case for every single database. Well, you could do that, but then you're just basically building an ORM.

Also, the real reason xo exists is that I work on a project that works with 3 different SQL databases, and was really annoyed by the complete inconsistency in naming of types/funcs across the databases, even though they were used in more or less the same way. 

In the spirit of Go, "generate all the things!".

**Comment by kenshaw** [comment]
To expound on that last comment, here's how I would generate `MostRecent` in the projects I work on:

```sh
for i in "table names"; do 
  xo -o models -N -M -B -T $i -a -I -f "$iMostRecent" << ENDSQL
SELECT * 
FROM $i 
ORDER BY created_at DESC LIMIT %%limit int%%
ENDSQL
done
```

**Comment by nathanleclaire** [comment]
> For instance, we would do it this way for things like your MostRecent example, since not every table may have a created or modified field as the case may be. I hope people can understand that the reason I chose to keep this kind of stuff out of xo's basic templates is that it would be unwieldy to support every single use case for every single database. Well, you could do that, but then you're just basically building an ORM.

Yes, definitely, I'm all for "minimal-by-default" and think the current balance is pretty decent --  I think that folks should add things on a case-by-case basis as they need them, for instance as you mentioned it doesn't make sense in every case to add a `MostRecent` func to every table.  I suspect with better examples hopefully folks will be able to get a bit further using custom templates.

> To expound on that last comment, here's how I would generate MostRecent in the projects I work on:

That's a cool example -- I'll have to take a look at that.

**Pull request merged**
