### PR TITLE
Handle multiple primary keys colums in sqlite.

### LINKED ISSUE #42: sqlite3 generator does not handle table constraints
Here is my test schema

CREATE TABLE user (
    user_id     TEXT NON NULL PRIMARY KEY,
    email       TEXT,
    first_name  TEXT,
    last_name   TEXT,
    headline    TEXT,
    profile_url TEXT,
    location    TEXT,
    username    TEXT,
    password     TEXT
);

CREATE TABLE id_provider
(
    provider_id TEXT NOT NULL,
    user_id     TEXT NOT NULL REFERENCES user( user_id ),
    network     TEXT,

```
PRIMARY KEY( provider_id, user_id )
```

);

If I remove the PRIMARY KEY table constraint it generates fine. With it the following error is generated

error: sql: Scan error on column index 5: sql/driver: couldn't convert 2 into type bool

Would it be possible to support composite primary keys? I need them for the project I'm working on and would like to use xo to save me some time. If not is there some sort of work around where I can still generate most of code using xo. 

Regards and thanks for making this work public.

### PR DESCRIPTION
**Pull request by turnkey-commerce**
Handle specially the fact that the pk column can have values larger than
1 for multiple PK's and should be scanned as an integer rather than a
bool.

Fixes #42

Actually I see that a previous PR was addressing this same specific issue in Sqlite.  While it doesn't address the more general problem of multiple  it does prevent the program from exiting in Sqlite and paves the way for it to at least work when the other problem is fixed.

### CODE REVIEW

**Comment by kenshaw** [comment]
I really appreciate this PR! I had no idea this was happening, as I don't exactly use SQLite on a regular basis. Thanks! Will merge shortly.

**Comment by kenshaw** [comment]
Ok, going slightly back on my last comment, as I realized you modified an auto generated file.

From the SQLite docs:

PRAGMA schema.table_info(table-name);

This pragma returns one row for each column in the named table. Columns in the result set include the column name, data type, whether or not the column can be NULL, and the default value for the column. The "pk" column in the result set is zero for columns that are not part of the primary key, and is the index of the column in the primary key for columns that are part of the primary key.

The table named in the table_info pragma can also be a view.

When I originally read the docs for this, I missed the part that the returned primary key field returned the column position (offset by one, I suppose) for composite keys. Wow that's really confusing, especially since if  off-by-one.

A couple things need to happen to fix this:
1) the "IsPrimaryKey" needs to be changed from bool -> int in the gen.sh (along with its name)
2) the sqlite loader needs to be modified to massage the data after the fact (like many of the other sqlite models also require)

I don't really have any complex SQLite schemas to test this against. Would it be possible then for me to push onto your PR so that you could test locally?

**Comment by turnkey-commerce** [comment]
Sorry that I missed that about those being generated files.  I certainly don't mind testing against some Sqlite schemas it if you push the changes to my PR, thanks for handling that.

**Comment by kenshaw** [comment]
Great, I'm in the process of fixing it now. Hopefully will have it done in a couple hours, but since it's the Christmas holiday and family is in town, may not have a lot of time to work on this until late tonight.

**Comment by turnkey-commerce** [comment]
Understand with the rush in the holidays, no rush and have a good one!

**Comment by kenshaw** [comment]
I've updated your PR. Could you test this out with some more complicate schemas? The /examples/django version is broken now for SQLite.

(for reference, the schema that was used in the django folder is taken from the base django installation. it was the only project that I was aware of that supported [almost] all the databases that xo supports, and has "complex" relationships. I'm sure I can fix the revised sqlite loader in this PR to work again with django, but this is the extent of what I can likely do today due to the holidays... would really appreciate your input/feedback here!)

**Comment by turnkey-commerce** [comment]
OK, will check it out.

**Comment by turnkey-commerce** [comment]
Hey Ken, Generation of the sqlite case I was testing for the multiple PK problem worked OK, but still need to check the Django case, will need to install Django.  Only other thing I noticed on sqlite is that you can explicitly set the type to a date, datetime, or timestamp and need to cover that case.  Am checking that out too.

Cheers,
James

**Comment by turnkey-commerce** [comment]
Update - I was able to figure out what was causing the issue with Django, there was a duplicated method due to it referencing an index for the primary key but then not recognizing that it had already processed the primary key from a pre-built index.  Also in my testing I found that the datetime columns weren't being mapped to the proper type and fixed that as well. Those fixes are available in the latest commit.

Merry Christmas!

**Comment by kenshaw** [comment]
:+1: 

Ok, I merged this -- sorry but I had some commits / messed up the rebase -- apologies! It's on the master branch now though.

**Comment by turnkey-commerce** [comment]
No worries, glad to help.

**Pull request closed without merging**
