### PR TITLE
Escape names in MySQL using backtick.

### PR DESCRIPTION
**Pull request by jjsil**
The default identifier quote character for MySQL is the backtick (`)
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
instead of the double quote (") used in Postgres
https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html

Add a MyEscape function that uses backticks, tests and update the
mysql template files to use double quotes for strings instead of
backticks.

### CODE REVIEW

**Comment by jjsil** [comment]
This is a fix for #90

**Comment by kenshaw** [comment]
It's funny that you're submitting this now. I had, just yesterday, written something almost identical.

The issue, however, is that causes problems with other databases, and if other modes are set for MySQL. The workaround that I found here is to execute the following SQL prior to running any `xo` generated queries:

```sql
SET sql_mode='ANSI';
```

You can see this in the recently added `pokedex/main.go` example.

**Comment by kenshaw** [comment]
Sorry, to clarify, I need to think about whether or not this should be added or not. There are issues with the templates and generating Go code in general, as any generated string now would need to be escaped.

This is a problem in the "custom queries". At the moment, there is no way to define the surrounding string quote identifier (you have to just specify it in the template), and wrapping all the various SQL calls would make the templates, in my opinion, practically unusable/understandable. This is partly a limitation of the Go template syntax. 

Imagine if every SQL call in the templates had to look like this:
```
{{quotestr `SELECT * FROM` }}
```

**Comment by jjsil** [comment]
Thanks for the quick reply! I had a feeling this might be controversial :) We don't use custom queries at the moment so I don't know how this would interact with those.

My thinking was that the default in MySQL should be the default in XO so that new users don't fall on the same "trap" and have to spend time figuring things out the same way I just did.

Either way, please let me know what you decide so that I make changes in our repo accordingly.

**Comment by kenshaw** [comment]
It's not controversial -- it just requires a certain amount of code maintenance. I agree, the `--escape-*` parameters should work out of the box with all the databases. The primary problem is that the same `*.query.go.tpl` is used for all the databases, and you'd at minimum need to add one for MySQL as well. I only realized the limitation of the existing `xo` templates yesterday, when I wrote up the `pokedex` example, as it has fields named `order` in the pokedex schema. I have no idea why this hasn't come up in the ~1 year existence of MySQL (or maybe it has, but I've not paid attention to it).

To be honest, forcing the ANSI mode seems like the right approach to me, as MySQL is the odd man out vs the other databases. One problem that I see is that there's a certain expectation that the code generated with `xo' will be used in conjunction with other SQL already written -- that other SQL (whether targeted for MySQL or otherwise) I would, hypothetically, like to be uniform with what `xo` generates.

Also, of note, is that there is only a "need" to escape the fields when there's a conflict with a reserved keyword. This is really one of those things where there are problems with either including this, or not including it. Not including it would require more documentation / handling further "support" inquiries via GitHub issues.

**Comment by kenshaw** [comment]
I'm thinking something like a general  `--escape-mode=ansi` is in order, which is default option that gets changed for MySQL. So maybe `--escape-mode=<ansi|mysql|smart>` or some such. With `smart` as the default. I really am trying not to add any more additional options to `xo` that aren't 100% necessary. I'll think about this over the next day and figure out if what you have here is the best approach or not.

**Comment by jjsil** [comment]
A reserved keyword is exactly what just bit me and prompted this, we have a column named "Key".

I did add a mysql.query.go.tpl in this change, so that I could change the quote character there as well. I can totally see how having multiple copies of that template would be a maintenance burden if you're making regular changes to it.

I'm now testing what happens if we set the sql_mode=ANSI in all our connections (using Params in https://godoc.org/github.com/go-sql-driver/mysql#Config). That seems to be working so far, so that might be an option, which could be documented in the README.

**Comment by kenshaw** [comment]
Yes; I'm updating the README.md now.

**Comment by kenshaw** [comment]
I've updated the `README.md`, and think that the right way to go is to just tell users to use the `sql_mode=ansi`. It will keep the different database loaders more or less the same.

**Comment by jjsil** [comment]
Sounds good, thanks for the quick turnaround.

**Pull request closed without merging**
