### PR TITLE
Also added the other network address types as strings

### PR DESCRIPTION
**Pull request by tlianza**
In the last PR I only added inet... here are the other two: https://www.postgresql.org/docs/9.1/static/datatype-net-types.html

### CODE REVIEW

**Comment by kenshaw** [comment]
Have you tested these? I don't have any schemas against which to test these, as we don't use these types in our schemas (not relevant, or if they are, just done as text/character field...).

**Comment by tlianza** [comment]
I haven't written code to/from the database with these types, but I have tested the fact that without this change, xo generates code that doesn't compile - it creates structs with "Cidr" as a type, for example. My schema does have cidr & inet, but doesn't have macaddr. I added that strictly for completeness. After this change, the structs are at least valid.

**Comment by kenshaw** [comment]
There's a `--custom-type-package` option for the xo command line that specifies the package to use. Assuming goimports can find that package, it'll be added to the generated files. The problem with the custom types like those, is you really need a `driver.Valuer` and the `sql.Scanner` interfaces to be implemented appropriately for each of those types. Unless the postgresql type is just an alias for a byte array, or a string, then I don't think these would work as expected.

**Comment by tlianza** [comment]
Yep, I think you're right.

**Pull request closed without merging**
